spring:
  application:
    name: resume-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/aicareer}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:saurabh}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - read:user
              - user:email

server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false

groq:
  api:
    key: ${GROQ_API_KEY:}

rapidapi:
  key: ${RAPIDAPI_KEY:}